### ISSUE TITLE
Consider renaming

### ISSUE THREAD

**Issue by chevdor** [paritytech/releng-scripts#16]
`rs` sounds like it could be `releng-scripts` but the readme provides another definition.
Moreover, `rs` is already an [existing tool](https://www.venea.net/man/rs(1)).
Finally, with lots of people around using Rust, the meaning of `rs` will probably be biased towards something about Rust.

**Comment by chevdor** [comment]
Since `rs` is the head tool of the `releng-scripts` repository, I would simply suggest calling it `releng-scripts`.
The container image is also called `paritytech/releng-scripts` so it would align everything.

It is longer but will avoid conflicts and confusion. Locally, users can decide to alias `releng-scripts` to `rs` or anything else for a shorter version and if they don't mind shadowing other `rs` commands.

**Comment by EgorPopelyaev** [comment]
I agree with @chevdor. `releng-scripts` sounds ok and `rs` would be associated with Rust related stuff.
