### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by chevdor** [paritytech/releng-scripts#27]
I was about to write:

> It would be useful if the various script could include a `version` command or flag.

It is probably easier to use tags. Is the repo in a state where we could tag and "release" a first version ?

**Comment by joao-paulo-parity** [comment]
> It would be useful if the various script could include a version command or flag

Why is it useful? And could we use the commit hash as the version?

> Is the repo in a state where we could tag and "release" a first version?

I don't see why not

**Comment by chevdor** [comment]
> Why is it useful? And could we use the commit hash as the version?

We need to know, from the logs of a run, which version was used so we know if those issues we see have been addressed already. Using the tag require to all the git information which we will likely not have in the case of a Docker container for instance.

> I don't see why not

OK, so we could create a first tag already.

**Comment by chevdor** [comment]
https://github.com/paritytech/releng-scripts/blob/master/VERSION has been added and the Docker container reponds to the new `version` command.
